### ISSUE TITLE
Transaction broadcast always return "error": "transaction expired"

### ISSUE THREAD

**Issue by sunny112** [gettyio/tronwallet-mobile#451] opened 2018-09-20 21:09 UTC
For offline sign, I pass private  key and transactionUnsigned value to RNTron.signTransaction(), try to get transcationSigned value. Then I combine the value of transcationSigned with nodeIp("54.236.37.243:50051") as an object, and post it to https://api.tronwallet.me/tron/transaction/broadcast. The return value always is {
    "error": "transaction expired",
    "errorRaw": {}
}.
How can I solve it?

**Comment by pedrobertao** [comment] 2018-09-20 21:14
You have to get a new transactionUnsigned. Every transactionUnsigned has a timestamp encrypted at and if you use the same transactionUnsigned it will give this error.

**Comment by sunny112** [comment] 2018-09-21 01:11
Sure, I did. Every time, I got the value of transactionUnsigned(from getTransferTransaction()), then I used another device(can not connect network, like a cold wallet) generate value of transactionSigned by transactionUnsigned value. 
Then,
      const transactionData = await this.getTransactionDetails(transactionSigned);
        if (transactionData) {
            this.submitTransaction(transactionData, transactionSigned.transaction)
        }else {
            console.log('Empty Transaction Data');
        }

submitTransaction = async (transactionData, transactionSigned) => {
            const transaction = this.getTransactionObject(transactionData);
            const code = await this.broadcastTransaction(transactionSigned);
            if (code === 'SUCCESS') {
                console.log(code);
            }else{
                console.log(code);
            }
    };
broadcastTransaction = async (transactionSigned) => {
    const nodeIp = '54.236.37.243:50051';
    const reqBody = {
        transactionSigned,
        node: nodeIp
    };
    fetch(tronWallet_api + '/transaction/broadcast', {
        method: 'POST',
        body: JSON.stringify(reqBody)
    })
        .then((response) => {
            if (response.status < 200 || response.status >= 300) {
                console.log(response);
            } else {
                response.json().then(
                    (result) => {
                        console.log(result);
                        return result;
                    }
                )}
        })
        .catch((error) => console.warn(error));
};

But, I still get error. Status:400
{
    "result": false,
    "code": "TRANSACTION_EXPIRATION_ERROR",
    "type": "TYPE_NOT_REGISTRED",
    "error": "transaction expired",
    "hash": "517c323042dabc4974610cb041e63e0630eef4151029faa14bf6b9822593dbca"
}

So, I would like to ask what time zone the RNTron.signTransaction() used? And is it possible the hot wallet time is different from cold wallet, so I get transaction expired all the time.

**Comment by pedrobertao** [comment] 2018-09-21 12:28
Ok. Timezone might have a important role in this. I will double check the RNTron signTransaction Method and get back to you. Meanwhile, did you try to use another Node IP to see if this error persists ? 
We have users around the world and from different Timezones. We haven't had any problems reported about submit transaction. The only difference is the Node IP

**Comment by sunny112** [comment] 2018-09-21 22:39
Yes, I tried different Node Ip, and I tried to change cold wallet device system time(+1 day or -1 day) as well.  I still got the same error.
![image](https://user-images.githubusercontent.com/18472241/45909008-746f1500-bdb4-11e8-9b19-bf2eedc66c23.png)

Where can I find the document for this broadcast api? I am thinking maybe I pass incorrect transactionUnsigned data, or I skip some steps?

**Comment by pedrobertao** [comment] 2018-09-21 22:49
There is no official documentation yet because we use it exclusively for TronWalletMe. The problem is not the broadcast API. The problem is the Sign Transaction. You are making some mistake while Building this Transaction Hash. 
Please, demonstrate again what are the steps the you are making to get this Transaction Signed. You don't have to provide any Private Key her but if you provide some of the data and APIs used I will be helpful.

**Comment by sunny112** [comment] 2018-09-21 23:06
import Bitcoin from 'react-native-bitcoinjs-lib';
import bip39 from "bip39";
import ethers from 'ethers';
![image](https://user-images.githubusercontent.com/18472241/45909572-5eaf1f00-bdb7-11e8-9f85-54fac72150d4.png)
Then I  can get ten private key pairs like "0/9":"0x77ba062ce0d30c3bec51ed1418027df6771673134a786fd8516f3cf433c9f674".
Remove 0x would be my private key. I use the private key to generate my address.

**Comment by pedrobertao** [comment] 2018-09-22 00:50
I'm not familiar with this piece of code but react-native-tron will only sign transactions that are from the TRON network. Also, the broadcast transaction are only for the tron network as well.

**Comment by sunny112** [comment] 2018-09-24 17:38
OK, thank you so much, I will compare my private key with the key which is react-native-tron generate.

**Comment by pedrobertao** [comment] 2018-09-24 22:54
Ok. I will close this for now. If you have any more doubts please feel free to contact us.

**Closed by pedrobertao** 2018-09-24 22:54 UTC

**Comment by sunny112** [comment] 2018-09-25 22:12
I am so sorry for bothering you again.
I tried to pass the signed data which was generate from react-native-tron to broadcast transaction, but it still didn't work. So I think the problem should not be private key. 
Could you help me figure out? I really no idea which parts bring this error.

	1. Using my hot wallet(my iphone) to get unsigned transaction data.
![image](https://user-images.githubusercontent.com/18472241/46046259-40a62f00-c0d5-11e8-919b-9e1f6f30e96f.png)
![image](https://user-images.githubusercontent.com/18472241/46046263-4439b600-c0d5-11e8-8a98-877443790ef5.png)
	After that, I got unsigned transaction data.
	
	2. Then I passed my private key and unsigned data to RNTron.signTransaction to get signed data. This step took place in my cold wallet(an android system device, can not connect network)
![image](https://user-images.githubusercontent.com/18472241/46046270-4c91f100-c0d5-11e8-8dec-03644589efc5.png)
	3. Just for testing broadcast function, so I just combine transactionSigned data with nodeIp to a object, and then using postman to post my request.
![image](https://user-images.githubusercontent.com/18472241/46046278-5582c280-c0d5-11e8-8837-1becb797570c.png)
The key pair was generate from react-native-tron ( It's just our testing account, just free to use)

{"password":"r5qAO6ZUTrca+HprmlE2gnPIpFcg+mu3TkecFWdmVaQ=","publicKey":"041220E9A73E2961118DB75BBE93D04ED5AB3C2A42F81162D0D483459C55D3D5505D510E0AA5ED32B1A4C7EED24B4B6B6998F77B35F4B3E398023ECDC0C0FC4626","privateKey":"AF9A803BA6544EB71AF87A6B9A51368273C8A45720FA6BB74E479C15676655A4","address":"TFBYwbP35dY6CpZpQqXfuNecqiF6gr2yTY"}
